language: ruby
rvm:
  - 2.6.3
script:
  - bundle install
  - bundle exec jekyll build
after_success:
  - git clone https://github.com/xbf321/xbf321.github.io.git
  - cd xbf321.github.io
  - rm -rf `ls  | grep -v _site`  && cp -r ./_site/* . && rm -rf _site
  - git config user.name "xbf321"
  - git config user.email "xbf321@gmail.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force https://$DEPLOY_TOKEN@github.com/xbf321/xbf321.github.io.git master
branches:
  only:
  - source
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
cache: bundler
notifications:
  email: false