language: ruby
rvm:
  - 2.6.3
before_script:
 - chmod +x ./script/cibuild # or do this locally and commit
script: ./script/cibuild
after_success:
  - git clone https://github.com/xbf321/www.xingbaifang.com.git
  - cd www.xingbaifang.com && rm -rf * && cp -r ../_site/* .
  - git config user.name "xbf321"
  - git config user.email "xbf321@gmail.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force https://$DEPLOY_TOKEN@github.com/xbf321/www.xingbaifang.com.git master
branches:
  only:
  - master
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false